apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: geni
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: {{ .Release.Name }}
