from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any
from pathlib import Path

@dataclass
class GeneratedFile:
    """A file generated by a template."""
    filename: str           # output filename
    content: Any            # dict for JSON/YAML, str for raw text
    file_type: str          # "tf.json", "yaml", "tf", "raw"

class TerraformJSON(GeneratedFile):
    """Terraform JSON file (.tf.json)"""
    def __init__(self, filename: str, content: dict):
        super().__init__(filename=filename, content=content, file_type="tf.json")

class TerraformHCL(GeneratedFile):
    """Raw Terraform HCL file (.tf)"""
    def __init__(self, filename: str, content: str):
        super().__init__(filename=filename, content=content, file_type="tf")

class KubernetesManifest(GeneratedFile):
    """Kubernetes YAML manifest"""
    def __init__(self, filename: str, content: dict | list[dict]):
        super().__init__(filename=filename, content=content, file_type="yaml")

class RawFile(GeneratedFile):
    """Any raw text file"""
    def __init__(self, filename: str, content: str, ext: str = "txt"):
        super().__init__(filename=filename, content=content, file_type=ext)

@dataclass
class RenderContext:
    """Context passed to template render methods."""
    params: dict[str, Any]
    data: dict[str, Any]
    resources: dict[str, Any]     # outputs from previously compiled resources
    templates_dir: Path
    output_dir: Path

class Template:
    """Base class for Python templates.

    Subclass this and implement render() to create custom templates.
    The render method receives params and data, returns GeneratedFile or list of GeneratedFile.
    """
    def __init__(self, name: str):
        self.name = name

    def render(self, context: RenderContext) -> GeneratedFile | list[GeneratedFile]:
        raise NotImplementedError(f"Template {self.__class__.__name__} must implement render()")
