---
# Source: opentelemetry-operator/templates/certmanager.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    helm.sh/chart: opentelemetry-operator-0.86.2
    app.kubernetes.io/name: opentelemetry-operator
    app.kubernetes.io/version: "0.122.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: opentelemetry-operator
    app.kubernetes.io/instance: opentelemetry-operator
    app.kubernetes.io/component: webhook
  name: opentelemetry-operator-serving-cert
  namespace: monitoring
spec:
  dnsNames:
    - opentelemetry-operator-webhook.monitoring.svc
    - opentelemetry-operator-webhook.monitoring.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: opentelemetry-operator-selfsigned-issuer
  secretName: opentelemetry-operator-controller-manager-service-cert
  subject:
    organizationalUnits:
      - opentelemetry-operator
---
# Source: opentelemetry-operator/templates/certmanager.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    helm.sh/chart: opentelemetry-operator-0.86.2
    app.kubernetes.io/name: opentelemetry-operator
    app.kubernetes.io/version: "0.122.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: opentelemetry-operator
    app.kubernetes.io/instance: opentelemetry-operator
    app.kubernetes.io/component: webhook
  name: opentelemetry-operator-selfsigned-issuer
  namespace: monitoring
spec:
  selfSigned: {}
