apiVersion: geni.io/v1alpha1
kind: Target
metadata:
  name: example-prod-v2
  labels:
    environment: production
    team: platform
spec:
  data:
    project: example-prod-1234
    region: us-central1
  output: compiled/terraform/example-prod-v2
  resources:
    backend:
      template: terraform_tf/backend.tf
      params:
        bucket_name: terraform-bucket-example
        tfstate_prefix: ${{ data.project }}

    provider:
      template: terraform_tf/provider.tf
      params:
        project_name: ${{ data.project }}

    instance:
      template: terraform_tf/instance.tf
      params:
        name: test-instance-1
        project_name: ${{ data.project }}

    cluster_autopilot:
      template: terraform_tf/cluster_autopilot.tf
      params:
        project_name: ${{ data.project }}
        region: ${{ data.region }}
